#This make file builds the kernel module for the running kernel as well as agianst the other kernel source.


obj-m += helloworld.o

THIS = "/lib/modules/$(shell uname -r)/build"

PWD = $(shell pwd)

# make this -> build module for the currently running kernel
all:
	make -C $(THIS) M=$(PWD) modules

# make all generic -> build the module for the other kernle source , which is given by command line argument
# USAGE : make KDIR=<path to linux source> generic
generic:
	make -C $(KDIR) M=$(PWD)  modules

# make clean -> removes all the file generated by make
clean:
	make -C $(THIS) M=$(PWD) clean
